"use strict";
let array1 = [5, 6, 7];
console.log(`Array 1: ${array1}`);
let array2 = [1, 2, 3];
console.log(`Array 2: ${array2}`);
let array3 = [];
console.log(`Array 3: ${array3}`);
let array5 = [];
array5.push(1234);
console.log(`Array 5: ${array5}`);
